# Generated by Django 3.1.2 on 2021-01-26 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=15)),
                ('password', models.CharField(max_length=32)),
                ('useremail', models.EmailField(max_length=254)),
                ('phonenum', models.CharField(max_length=11)),
                ('from_right', models.IntegerField(choices=[(1, '管理员'), (2, '员工'), (3, '客户')])),
            ],
        ),
    ]
