# Generated by Django 3.1.2 on 2021-01-26 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserToken',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=32)),
                ('start_time', models.DateTimeField()),
            ],
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='phonenum',
            field=models.CharField(max_length=11, unique=True),
        ),
    ]
