# Generated by Django 3.1.2 on 2021-01-26 16:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20210126_1524'),
    ]

    operations = [
        migrations.AddField(
            model_name='usertoken',
            name='user',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='account.userinfo'),
            preserve_default=False,
        ),
    ]
