# Generated by Django 3.1.2 on 2021-01-26 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
        ('account', '0003_usertoken_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='from_product',
            field=models.ManyToManyField(to='product.Product'),
        ),
    ]
