# Generated by Django 3.1.2 on 2021-02-03 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_userinfo_from_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='user_id',
            field=models.CharField(default=1, max_length=64),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userinfo',
            name='user_secret',
            field=models.CharField(default=1, max_length=64),
            preserve_default=False,
        ),
    ]
