# Generated by Django 3.1.2 on 2021-02-04 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_auto_20210203_1350'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='useremail',
            field=models.EmailField(max_length=254, null=True),
        ),
    ]
