# Generated by Django 3.1.2 on 2021-03-23 09:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_auto_20210204_0928'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userinfo',
            old_name='from_right',
            new_name='from_privilege',
        ),
    ]
