# Generated by Django 3.1.2 on 2021-03-23 16:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_auto_20210323_0904'),
    ]

    operations = [
        migrations.AddField(
            model_name='usertoken',
            name='end_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 23, 16, 36, 5, 46281)),
        ),
    ]
