# Generated by Django 3.1.2 on 2021-03-23 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_usertoken_end_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usertoken',
            name='end_time',
            field=models.DateTimeField(),
        ),
    ]
