# Generated by Django 3.1.2 on 2021-05-19 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_auto_20210323_1637'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='useremail',
            field=models.EmailField(max_length=254, null=True, unique=True),
        ),
    ]
