# Generated by Django 3.1.2 on 2021-05-27 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0010_auto_20210519_1409'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userinfo',
            old_name='phonenum',
            new_name='phone_num',
        ),
        migrations.RenameField(
            model_name='userinfo',
            old_name='useremail',
            new_name='user_email',
        ),
        migrations.RenameField(
            model_name='usertoken',
            old_name='user',
            new_name='fk_user',
        ),
        migrations.RemoveField(
            model_name='userinfo',
            name='from_privilege',
        ),
        migrations.RemoveField(
            model_name='userinfo',
            name='from_product',
        ),
        migrations.AddField(
            model_name='userinfo',
            name='privilege',
            field=models.IntegerField(choices=[(1, '管理员'), (2, '生产部'), (3, '销售财务部'), (99, '其他部门')], default=1),
            preserve_default=False,
        ),
    ]
