# Generated by Django 3.1.2 on 2021-08-06 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0014_loginlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='remote_control',
            field=models.BooleanField(default=False),
        ),
    ]
