# Generated by Django 3.1.2 on 2021-01-26 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productname', models.CharField(max_length=32)),
                ('productkey', models.CharField(max_length=64)),
                ('product_servo_num', models.IntegerField()),
            ],
        ),
    ]
