# Generated by Django 3.1.2 on 2021-01-30 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_servo_num',
            field=models.IntegerField(null=True),
        ),
    ]
