# Generated by Django 3.1.2 on 2021-03-18 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_auto_20210130_1548'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_identifier',
            field=models.CharField(default='LSW', max_length=10),
        ),
        migrations.AddField(
            model_name='product',
            name='product_type',
            field=models.CharField(default='test', max_length=18),
        ),
    ]
