# Generated by Django 3.1.2 on 2021-03-23 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_auto_20210318_1721'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_identifier',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
