# Generated by Django 3.1.2 on 2021-05-27 17:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_auto_20210323_0947'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='productkey',
            new_name='product_key',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='productname',
            new_name='product_name',
        ),
    ]
