# Generated by Django 3.1.2 on 2021-05-10 09:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='otherInfo',
            new_name='taskInfo',
        ),
    ]
