# Generated by Django 3.1.2 on 2021-05-10 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20210510_0910'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='taskInfo',
            field=models.TextField(null=True),
        ),
    ]
