# Generated by Django 3.1.2 on 2021-05-10 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20210510_0914'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='taskSubmitUrl',
            field=models.URLField(null=True),
        ),
    ]
