# Generated by Django 3.1.2 on 2021-05-10 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_task_tasksubmiturl'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='taskSubmitInfo',
            field=models.CharField(max_length=64, null=True),
        ),
    ]
