# Generated by Django 3.1.2 on 2021-05-27 17:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_task_tasksubmitinfo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='taskId',
            new_name='task_id',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='taskInfo',
            new_name='task_info',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='taskSubmitInfo',
            new_name='task_submit_info',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='taskSubmitUrl',
            new_name='task_submit_url',
        ),
    ]
