# Generated by Django 3.1.2 on 2021-03-14 16:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('device', '0007_auto_20210205_1639'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlarmInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alarm_name', models.CharField(max_length=16)),
                ('alarm_info', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='Run',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('run_starttime', models.DateTimeField()),
                ('run_endtime', models.DateTimeField(null=True)),
                ('from_device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='device.device')),
            ],
        ),
        migrations.CreateModel(
            name='Alarm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_servo', models.IntegerField(choices=[(1, 'Error_1'), (2, 'Error_2'), (3, 'Error_3'), (4, 'Error_4')])),
                ('alarm_starttime', models.DateTimeField()),
                ('alarm_endtime', models.DateTimeField(null=True)),
                ('alarm_status', models.IntegerField(choices=[(0, '报警解除'), (1, '正在报警')])),
                ('from_alarm_info', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='log.alarminfo')),
                ('from_device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='device.device')),
            ],
        ),
    ]
