# Generated by Django 3.1.2 on 2021-03-22 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('log', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alarm',
            name='from_device',
        ),
        migrations.RemoveField(
            model_name='run',
            name='from_device',
        ),
        migrations.AddField(
            model_name='alarm',
            name='device_name',
            field=models.CharField(default=1, max_length=64, verbose_name='设备标识名称'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='run',
            name='device_name',
            field=models.CharField(default=1, max_length=64, verbose_name='设备标识名称'),
            preserve_default=False,
        ),
    ]
