"""
Django settings for project_21_01_25 project.

Generated by 'django-admin startproject' using Django 3.1.2.

For more information on this file, see
https://docs.djangoproject.com/en/3.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.1/ref/settings/
"""

from pathlib import Path
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '2lsvqs+1kzheh!4t8+4xj^5-5ggmto0a%ozfwbtisas+-fvi#0'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*', ]

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'account',
    'device',
    'product',
    'api',
    'homepage',
    'log',
    'weixin',
    'sale'
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'project_21_01_25.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')]
        ,
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'project_21_01_25.wsgi.application'

# Database
# https://docs.djangoproject.com/en/3.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'HOST': 'localhost',
        'USER': 'root',
        'PASSWORD': '1234',
        'PORT': 3306,
        'NAME': 'spc_drf_db',
        'OPTIONS': {
            "init_command": "SET foreign_key_checks = 0;",
        }
    }
}

# Password validation
# https://docs.djangoproject.com/en/3.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
# https://docs.djangoproject.com/en/3.1/topics/i18n/

LANGUAGE_CODE = 'zh-hans'

TIME_ZONE = 'Asia/shanghai'

USE_I18N = True

USE_L10N = True

USE_TZ = False

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.1/howto/static-files/

STATIC_URL = '/static/'

# import rest_framework.renderers.BrowsableAPIRenderer
REST_FRAMEWORK = {
    # 认证
    'DEFAULT_AUTHENTICATION_CLASSES': ['utils.auth.Authtiction', ],
    'UNAUTHENTICATED_USER': None,
    'UNAUTHENTICATED_TOKEN': None,
    'DEFAULT_RENDERER_CLASSES': ['rest_framework.renderers.JSONRenderer',
                                 # 'rest_framework.renderers.HTMLFormRenderer',
                                 'rest_framework.renderers.BrowsableAPIRenderer'],
    # 'EXCEPTION_HANDLER': 'device.utils.exception.exception_handler',
    # 版本控制
    "DEFAULT_VERSIONING_CLASS": "rest_framework.versioning.URLPathVersioning",
    "DEFAULT_VERSION": 'v1',
    "ALLOWED_VERSIONS": ['v1', 'v2'],
    "VERSION_PARAM": 'version',
    # 'EXCEPTION_HANDLER': 'utils.exception.exception_handler',
}

# 项目中需要用到的属性列表
# 阿里云接口实例名称
IOT_INSTANCE_ID = "iot-cn-st21tyzcm06"
# 任务的基础属性（v1用）
TASK_BASICS_PROPERTIES = ['leftLength', 'rightLength', 'leftAngle', 'rightAngle', 'length', 'angle', 'loopback', 'arc']
# 任务的其他属性（v1用）
TASK_OTHER_PROPERTIES = ['TaskNum', 'NumberRoots']
# 伺服驱动器属性
SERVO_PROPERTIES = ['Voltage', 'Speed', 'Current', 'Torque']
# 生成任务属性时需要生成的其他属性（后续会与任务的其他属性进行合并）
TAG_TASK_PROPERTIES = ["count", "diameter"]
# 查询任务时需要额外查询的属性
TASK_QUERY_PROPERTIES = ["status", "diameter", "quantityCount", "count"]
# 各个产品系列对应的查询属性名称(v2用)
PRODUCT_PROPERTIES = [
    # 弯曲中心
    {
        "product": ["g0p4lIsqPV6"],
        "property": {
            "list": ['leftLength', 'rightLength', 'leftAngle', 'rightAngle'],
            "int": [
                {"key": 'count', "name": "计划产量"},
                {"key": 'diameter', "name": "钢筋直径"},
            ]
        }
    },
    # 一体机系列
    {
        "product": ["g0p4txvTEE5", "g0p4nlVxOkV"],
        "property": {
            "list": ['length', 'angle', 'loopback', 'arc'],
            "int": [
                {"key": 'count', "name": "计划产量"},
                {"key": 'diameter', "name": "钢筋直径"},
            ]
        }
    },
    # 剪切锯切系列
    {
        "product": ["g0p4RUnQtgI", "g0p4nTrjfyq"],
        "property": {
            "list": [],
            "int": [
                {"key": 'length', "name": "加工长度"},
                {"key": 'times', "name": "加工次数"},
                {"key": 'diameter', "name": "钢筋直径"},
            ]
        }
    },
    # 滚笼焊系列
    {
        "product": ["g0p4tpPud99"],
        "property": {
            "list": [],
            "int": []
        }
    },
    # 高速调直机系列
    {
        "product": ["g0p4DBrYoGw"],
        "property": {
            "list": [],
            "int": [
                {"key": 'length', "name": "加工长度"},
                {"key": 'count', "name": "计划产量"},
                {"key": 'diameter', "name": "钢筋直径"},
            ]
        }
    },
    # 五机头系列
    {
        "product": ["g0p4iqEI2V5"],
        "property": {
            "list": [],
            "int": []
        }
    }
]