# Generated by Django 3.1.2 on 2021-01-26 17:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product', '0001_initial'),
        ('account', '0004_userinfo_from_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nick_name', models.CharField(max_length=32, null=True, verbose_name='设备备注名称')),
                ('device_name', models.CharField(max_length=64, verbose_name='设备标识名称')),
                ('device_secret', models.CharField(max_length=64)),
                ('from_device_secret', models.CharField(max_length=64, null=True, verbose_name='设备序列号')),
                ('from_DTU_MAC', models.CharField(max_length=15, null=True)),
                ('device_type', models.IntegerField(null=True)),
                ('from_product', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='product.product')),
                ('from_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.userinfo')),
            ],
        ),
    ]
