# Generated by Django 3.1.2 on 2021-01-27 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('device', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='iot_id',
            field=models.CharField(default=1, max_length=64),
            preserve_default=False,
        ),
    ]
