# Generated by Django 3.1.2 on 2021-02-04 08:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_auto_20210203_1350'),
        ('device', '0003_auto_20210129_1406'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='from_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='account.userinfo'),
        ),
    ]
