# Generated by Django 3.1.2 on 2021-02-05 08:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_auto_20210130_1548'),
        ('device', '0004_auto_20210204_0843'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='from_product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.product'),
        ),
    ]
