# Generated by Django 3.1.2 on 2021-02-05 09:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('device', '0005_auto_20210205_0819'),
    ]

    operations = [
        migrations.RenameField(
            model_name='device',
            old_name='from_device_secret',
            new_name='actual_device_secret',
        ),
        migrations.RenameField(
            model_name='device',
            old_name='from_DTU_MAC',
            new_name='module_secret',
        ),
    ]
