# Generated by Django 3.1.2 on 2021-02-05 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('device', '0006_auto_20210205_0926'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='actual_device_secret',
            field=models.CharField(max_length=64, null=True, unique=True, verbose_name='设备序列号'),
        ),
        migrations.AlterField(
            model_name='device',
            name='module_secret',
            field=models.CharField(max_length=15, null=True, unique=True),
        ),
    ]
