# Generated by Django 3.1.2 on 2021-03-15 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('device', '0007_auto_20210205_1639'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='device_type',
            field=models.IntegerField(default=2),
        ),
    ]
