# Generated by Django 3.1.2 on 2021-03-16 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('device', '0008_auto_20210315_1438'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='device_latitude',
            field=models.FloatField(default=30.969819),
        ),
        migrations.AddField(
            model_name='device',
            name='device_longitude',
            field=models.FloatField(default=103.984727),
        ),
    ]
