# Generated by Django 3.1.2 on 2021-03-16 14:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_auto_20210204_0928'),
        ('device', '0009_auto_20210316_0809'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='from_user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='account.userinfo'),
        ),
    ]
