# Generated by Django 3.1.2 on 2021-03-25 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('device', '0010_auto_20210316_1406'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='actual_device_secret',
            field=models.CharField(max_length=32, null=True, unique=True, verbose_name='设备序列号'),
        ),
        migrations.AlterField(
            model_name='device',
            name='module_secret',
            field=models.CharField(max_length=32, null=True, unique=True),
        ),
    ]
