# Generated by Django 3.1.2 on 2021-04-06 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('device', '0012_auto_20210406_1458'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='device_TotalOutput',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='device',
            name='device_TotalRunTime',
            field=models.IntegerField(default=0),
        ),
    ]
