# Generated by Django 3.1.2 on 2021-04-10 10:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_auto_20210323_1637'),
        ('device', '0013_auto_20210406_1606'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='from_user',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='account.userinfo'),
        ),
    ]
