# Generated by Django 3.1.2 on 2021-04-29 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('device', '0014_auto_20210410_1041'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='deviceCity',
            field=models.CharField(default='成都', max_length=6),
        ),
    ]
