# Generated by Django 3.1.2 on 2021-04-29 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('device', '0015_device_devicecity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='device',
            name='deviceCity',
        ),
        migrations.AddField(
            model_name='device',
            name='deviceProvince',
            field=models.CharField(default='四川', max_length=6),
        ),
    ]
