# Generated by Django 3.1.2 on 2021-05-18 16:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('device', '0018_device_deviceauthorizedate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='device',
            name='deviceAuthorizeDate',
        ),
    ]
