# Generated by Django 3.1.2 on 2021-05-25 15:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('device', '0020_salesinfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='fk_sales',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='device.salesinfo'),
        ),
    ]
