# Generated by Django 3.1.2 on 2021-05-26 14:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sale', '0001_initial'),
        ('device', '0021_device_fk_sales'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='fk_sales',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='sale.salesinfo'),
        ),
        migrations.DeleteModel(
            name='SalesInfo',
        ),
    ]
