# Generated by Django 3.1.2 on 2021-05-26 14:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sale', '0001_initial'),
        ('device', '0022_auto_20210526_1447'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='fk_sales',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='sale.salesinfo'),
        ),
    ]
