# Generated by Django 3.1.2 on 2021-05-26 15:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sale', '0003_remove_salesinfo_fk_devices'),
        ('device', '0024_remove_device_fk_sales'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='fk_sales',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='sale.salesinfo'),
        ),
    ]
