# Generated by Django 3.1.2 on 2021-05-27 17:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('device', '0026_auto_20210527_1735'),
    ]

    operations = [
        migrations.RenameField(
            model_name='device',
            old_name='deviceOnLock',
            new_name='device_lock',
        ),
        migrations.RenameField(
            model_name='device',
            old_name='deviceProvince',
            new_name='device_province',
        ),
        migrations.RenameField(
            model_name='device',
            old_name='from_user',
            new_name='fk_user',
        ),
    ]
