# Generated by Django 3.1.2 on 2021-05-31 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('device', '0027_auto_20210527_1749'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='hmi_secret',
            field=models.CharField(max_length=32, null=True, unique=True),
        ),
    ]
