# Generated by Django 3.1.2 on 2021-06-05 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('device', '0028_device_hmi_secret'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='module_secret_two',
            field=models.CharField(max_length=32, null=True, unique=True),
        ),
    ]
