# Generated by Django 3.1.2 on 2021-06-08 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('device', '0029_device_module_secret_two'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='device_product_name',
            field=models.CharField(max_length=32, null=True),
        ),
    ]
