# Generated by Django 3.1.2 on 2021-06-18 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('device', '0030_device_device_product_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='device_Boolean',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='device',
            name='device_DelayLock',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='device',
            name='device_Time',
            field=models.DateTimeField(null=True),
        ),
    ]
