# Generated by Django 3.1.2 on 2021-06-18 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('device', '0031_auto_20210618_1706'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='device',
            name='device_Boolean',
        ),
        migrations.AddField(
            model_name='device',
            name='device_lock_status',
            field=models.BooleanField(default=False, verbose_name='设备锁定状态'),
        ),
        migrations.AlterField(
            model_name='device',
            name='device_DelayLock',
            field=models.BooleanField(default=False, verbose_name='延迟锁定标志'),
        ),
        migrations.AlterField(
            model_name='device',
            name='device_Time',
            field=models.DateTimeField(null=True, verbose_name='延迟日期'),
        ),
    ]
