# Generated by Django 3.1.2 on 2021-06-18 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('device', '0032_auto_20210618_1750'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='device',
            name='device_Time',
        ),
        migrations.AddField(
            model_name='device',
            name='device_date',
            field=models.DateField(null=True, verbose_name='延迟日期'),
        ),
    ]
