# Generated by Django 3.1.2 on 2021-05-26 15:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sale', '0002_salesinfo_fk_devices'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salesinfo',
            name='fk_devices',
        ),
    ]
