# Generated by Django 3.1.2 on 2021-06-23 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sale', '0005_auto_20210611_1111'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesinfo',
            name='customer_code',
            field=models.CharField(max_length=64, verbose_name='客户代码'),
        ),
    ]
